# Generated by Django 4.1.7 on 2023-04-26 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_alter_modelo_emailusuario_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='avatar',
        ),
    ]
