# Generated by Django 4.1.7 on 2023-04-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_modelo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fechaComentario',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='diseño',
            field=models.CharField(choices=[('arte', 'Arte'), ('moda', 'Moda'), ('joya', 'Joya'), ('casa', 'Casa'), ('arquitectura', 'Arquitectura'), ('artilugio', 'Artilugio'), ('juego', 'Juego'), ('herramienta', 'Herramienta'), ('otro', 'Otro')], default='otro', max_length=15),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='fechaPost',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
