# Generated by Django 4.1.7 on 2023-04-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0006_alter_comentario_fechacomentario_alter_modelo_diseño_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='diseño',
            field=models.IntegerField(choices=[('arte', 'Arte'), ('moda', 'Moda'), ('joya', 'Joya'), ('casa', 'Casa'), ('arquitectura', 'Arquitectura'), ('artilugio', 'Artilugio'), ('juego', 'Juego'), ('herramienta', 'Herramienta'), ('otro', 'Otro')]),
        ),
    ]
