# Generated by Django 4.1.7 on 2023-04-27 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0008_alter_modelo_diseño'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='emailUsuario',
        ),
    ]
