# Generated by Django 4.1.7 on 2023-04-27 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0010_alter_comentario_nombre_alter_modelo_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelo',
            options={'ordering': ['-fechaPost']},
        ),
    ]
