# Generated by Django 4.1.7 on 2023-04-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0011_alter_modelo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelo',
            options={},
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fechaComentario',
            field=models.DateField(auto_now_add=True),
        ),
    ]
