# Generated by Django 4.1.7 on 2023-04-28 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0015_alter_comentario_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
