# Generated by Django 4.1.7 on 2023-04-28 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0017_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='model_id',
            new_name='modelo',
        ),
    ]
