# Generated by Django 4.1.7 on 2023-05-03 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0022_mensaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
