# Generated by Django 4.1.7 on 2023-05-04 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Base', '0025_delete_comentario_delete_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='post')),
                ('diseño', models.CharField(choices=[('arte', 'Arte'), ('moda', 'Moda'), ('joya', 'Joya'), ('casa', 'Casa'), ('arquitectura', 'Arquitectura'), ('artilugio', 'Artilugio'), ('juego', 'Juego'), ('herramienta', 'Herramienta'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.CharField(max_length=500)),
                ('fechaPost', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='Base.modelo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
